In [1]:
import pandas as pd
import numpy as np
from bs4 import BeautifulSoup
import requests
import io
from datetime import datetime
import matplotlib.pyplot as plt
import seaborn as sns
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [2]:
import pandas as pd
from datetime import datetime
import numpy as np
import requests
import io

In [3]:
!pip install sparse

Requirement already satisfied: sparse in /usr/local/lib/python3.10/dist-packages (0.14.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.10/dist-packages (from sparse) (1.23.5)
Requirement already satisfied: scipy>=0.19 in /usr/local/lib/python3.10/dist-packages (from sparse) (1.10.1)
Requirement already satisfied: numba>=0.49 in /usr/local/lib/python3.10/dist-packages (from sparse) (0.56.4)
Requirement already satisfied: llvmlite<0.40,>=0.39.0dev0 in /usr/local/lib/python3.10/dist-packages (from numba>=0.49->sparse) (0.39.1)
Requirement already satisfied: setuptools in /usr/local/lib/python3.10/dist-packages (from numba>=0.49->sparse) (67.7.2)

In [4]:
import sparse

In [5]:
import os
os.chdir('/content/drive/MyDrive/Colab Notebooks')

In [6]:
data_path = 'london-bss-colab/data_summer/tripcsvbame-summer.csv'

In [7]:
data=pd.read_csv(data_path)

In [8]:
data_path = 'https://cycling.data.tfl.gov.uk/usage-stats/'

In [9]:
data['usage-stats/']  = data['usage-stats/'].apply(lambda x: x.strip())

In [10]:
def read_url(url):
    s=requests.get(url).content
    c=pd.read_csv(io.StringIO(s.decode('utf-8')))
    return c

In [11]:
frames = []
for x in data['usage-stats/']:
    frames.append(read_url(data_path + x))

result = pd.concat(frames)
result.columns

Index(['Rental Id', 'Duration', 'Bike Id', 'End Date', 'EndStation Id',
       'EndStation Name', 'Start Date', 'StartStation Id', 'StartStation Name',
       'Number', 'Start date', 'Start station number', 'Start station',
       'End date', 'End station number', 'End station', 'Bike number',
       'Bike model', 'Total duration', 'Total duration (ms)'],
      dtype='object')

In [12]:
result['Total duration (ms)'] = result['Total duration (ms)']/1000

In [13]:
result

,Rental Id,Duration,Bike Id,End Date,EndStation Id,EndStation Name,Start Date,StartStation Id,StartStation Name,Number,Start date,Start station number,Start station,End date,End station number,End station,Bike number,Bike model,Total duration,Total duration (ms)
0,121447141.0,420.0,18241.0,16/06/2022 14:14,500.0,"Ansell House, Stepney",16/06/2022 14:07,542.0,"Salmon Lane, Limehouse",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,121592389.0,840.0,23053.0,19/06/2022 21:43,252.0,"Jubilee Gardens, South Bank",19/06/2022 21:29,195.0,"Milroy Walk, South Bank",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,121592583.0,900.0,23053.0,19/06/2022 21:58,92.0,"Borough Road, Elephant & Castle",19/06/2022 21:43,252.0,"Jubilee Gardens, South Bank",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,121605480.0,960.0,22373.0,20/06/2022 11:04,810.0,"Tate Modern, Bankside",20/06/2022 10:48,427.0,"Cheapside, Bank",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,121631962.0,1200.0,17691.0,20/06/2022 20:19,92.0,"Borough Road, Elephant & Castle",20/06/2022 19:59,645.0,"Great Suffolk Street, The Borough",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
186429,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,125230184.0,2022-09-19 00:00,003427,"Fanshaw Street, Hoxton",2022-09-19 00:14,200014,"Gunmakers Lane, Old Ford",57421.0,CLASSIC,13m 50s,830.650
186430,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,125230185.0,2022-09-19 00:00,001007,"Drury Lane, Covent Garden",2022-09-19 00:10,001194,"Westminster University, Marylebone",17815.0,CLASSIC,9m 32s,572.144
186431,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,125230186.0,2022-09-19 00:00,001097,"Northumberland Avenue, Strand",2022-09-19 00:08,000988,"Great Russell Street, Bloomsbury",51520.0,CLASSIC,7m 14s,434.071
186432,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,125230187.0,2022-09-19 00:00,022183,"Crinan Street, King's Cross",2022-09-19 00:22,300081,"Haggerston Road, Haggerston",51557.0,CLASSIC,21m 59s,1319.606
186433,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,125230188.0,2022-09-19 00:00,300082,"Bridge Avenue, Hammersmith",2022-09-19 00:31,001193,"Kensington Gore, Knightsbridge",51804.0,CLASSIC,30m 21s,1821.003

In [14]:
result.columns

Index(['Rental Id', 'Duration', 'Bike Id', 'End Date', 'EndStation Id',
       'EndStation Name', 'Start Date', 'StartStation Id', 'StartStation Name',
       'Number', 'Start date', 'Start station number', 'Start station',
       'End date', 'End station number', 'End station', 'Bike number',
       'Bike model', 'Total duration', 'Total duration (ms)'],
      dtype='object')

In [15]:
# combining values
result['rentalid'] = result['Rental Id'].fillna(result['Number'])
result['duration'] = result['Duration'].fillna(result['Total duration (ms)'])
result['endstationname'] = result['EndStation Name'].fillna(result['End station'])
result['startstationname'] = result['StartStation Name'].fillna(result['Start station'])
result['startdate'] = result['Start Date'].fillna(result['Start date'])

In [16]:
result

,Rental Id,Duration,Bike Id,End Date,EndStation Id,EndStation Name,Start Date,StartStation Id,StartStation Name,Number,...,End station,Bike number,Bike model,Total duration,Total duration (ms),rentalid,duration,endstationname,startstationname,startdate
0,121447141.0,420.0,18241.0,16/06/2022 14:14,500.0,"Ansell House, Stepney",16/06/2022 14:07,542.0,"Salmon Lane, Limehouse",NaN,...,NaN,NaN,NaN,NaN,NaN,121447141.0,420.000,"Ansell House, Stepney","Salmon Lane, Limehouse",16/06/2022 14:07
1,121592389.0,840.0,23053.0,19/06/2022 21:43,252.0,"Jubilee Gardens, South Bank",19/06/2022 21:29,195.0,"Milroy Walk, South Bank",NaN,...,NaN,NaN,NaN,NaN,NaN,121592389.0,840.000,"Jubilee Gardens, South Bank","Milroy Walk, South Bank",19/06/2022 21:29
2,121592583.0,900.0,23053.0,19/06/2022 21:58,92.0,"Borough Road, Elephant & Castle",19/06/2022 21:43,252.0,"Jubilee Gardens, South Bank",NaN,...,NaN,NaN,NaN,NaN,NaN,121592583.0,900.000,"Borough Road, Elephant & Castle","Jubilee Gardens, South Bank",19/06/2022 21:43
3,121605480.0,960.0,22373.0,20/06/2022 11:04,810.0,"Tate Modern, Bankside",20/06/2022 10:48,427.0,"Cheapside, Bank",NaN,...,NaN,NaN,NaN,NaN,NaN,121605480.0,960.000,"Tate Modern, Bankside","Cheapside, Bank",20/06/2022 10:48
4,121631962.0,1200.0,17691.0,20/06/2022 20:19,92.0,"Borough Road, Elephant & Castle",20/06/2022 19:59,645.0,"Great Suffolk Street, The Borough",NaN,...,NaN,NaN,NaN,NaN,NaN,121631962.0,1200.000,"Borough Road, Elephant & Castle","Great Suffolk Street, The Borough",20/06/2022 19:59
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
186429,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,125230184.0,...,"Gunmakers Lane, Old Ford",57421.0,CLASSIC,13m 50s,830.650,125230184.0,830.650,"Gunmakers Lane, Old Ford","Fanshaw Street, Hoxton",2022-09-19 00:00
186430,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,125230185.0,...,"Westminster University, Marylebone",17815.0,CLASSIC,9m 32s,572.144,125230185.0,572.144,"Westminster University, Marylebone","Drury Lane, Covent Garden",2022-09-19 00:00
186431,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,125230186.0,...,"Great Russell Street, Bloomsbury",51520.0,CLASSIC,7m 14s,434.071,125230186.0,434.071,"Great Russell Street, Bloomsbury","Northumberland Avenue, Strand",2022-09-19 00:00
186432,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,125230187.0,...,"Haggerston Road, Haggerston",51557.0,CLASSIC,21m 59s,1319.606,125230187.0,1319.606,"Haggerston Road, Haggerston","Crinan Street, King's Cross",2022-09-19 00:00
186433,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,125230188.0,...,"Kensington Gore, Knightsbridge",51804.0,CLASSIC,30m 21s,1821.003,125230188.0,1821.003,"Kensington Gore, Knightsbridge","Bridge Avenue, Hammersmith",2022-09-19 00:00

In [17]:
result_general = result[['rentalid','duration','endstationname','startstationname','startdate']]

In [18]:
result_general.columns

Index(['rentalid', 'duration', 'endstationname', 'startstationname',
       'startdate'],
      dtype='object')

In [19]:
# dict_columns = {
#     "Rental Id": "RentalId",
#     'StartStation Name' : 'StartStationName',
#     'StartStation Name': 'EndStationName',
#     'Start Date': 'StartDate'
# }

In [20]:
# result_general = result_general.rename(columns=dict_columns)
# result_general['Duration'] = result_general['Duration']/1000
# result_general

In [21]:
result_general['startdate']

0         16/06/2022 14:07
1         19/06/2022 21:29
2         19/06/2022 21:43
3         20/06/2022 10:48
4         20/06/2022 19:59
                ...
186429    2022-09-19 00:00
186430    2022-09-19 00:00
186431    2022-09-19 00:00
186432    2022-09-19 00:00
186433    2022-09-19 00:00
Name: startdate, Length: 3935072, dtype: object

In [22]:
result_general.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3935072 entries, 0 to 186433
Data columns (total 5 columns):
 #   Column            Dtype
---  ------            -----
 0   rentalid          float64
 1   duration          float64
 2   endstationname    object
 3   startstationname  object
 4   startdate         object
dtypes: float64(2), object(3)
memory usage: 180.1+ MB

In [23]:
%%time
date_format = '%d/%m/%Y %H:%M:%S'
# result_general['End date']=pd.to_datetime(result_general['End date'])

result_general['startdate']=pd.to_datetime(result_general['startdate'])
# # # .dt.strftime('%Y-%m-%d %H:%m')
# # result_general

# test=result_general[result_general['startdate'].str.contains('/')]
# test['startdate']=pd.to_datetime(test['startdate'])

CPU times: user 4min 48s, sys: 889 ms, total: 4min 49s
Wall time: 4min 49s

<timed exec>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [24]:
result_general.head()

,rentalid,duration,endstationname,startstationname,startdate
0,121447141.0,420.0,"Ansell House, Stepney","Salmon Lane, Limehouse",2022-06-16 14:07:00
1,121592389.0,840.0,"Jubilee Gardens, South Bank","Milroy Walk, South Bank",2022-06-19 21:29:00
2,121592583.0,900.0,"Borough Road, Elephant & Castle","Jubilee Gardens, South Bank",2022-06-19 21:43:00
3,121605480.0,960.0,"Tate Modern, Bankside","Cheapside, Bank",2022-06-20 10:48:00
4,121631962.0,1200.0,"Borough Road, Elephant & Castle","Great Suffolk Street, The Borough",2022-06-20 19:59:00

In [25]:
result_general.shape

(3935072, 5)

In [26]:
result_general.sort_values(by='startdate',ignore_index=True)
result_general.head()

,rentalid,duration,endstationname,startstationname,startdate
0,121447141.0,420.0,"Ansell House, Stepney","Salmon Lane, Limehouse",2022-06-16 14:07:00
1,121592389.0,840.0,"Jubilee Gardens, South Bank","Milroy Walk, South Bank",2022-06-19 21:29:00
2,121592583.0,900.0,"Borough Road, Elephant & Castle","Jubilee Gardens, South Bank",2022-06-19 21:43:00
3,121605480.0,960.0,"Tate Modern, Bankside","Cheapside, Bank",2022-06-20 10:48:00
4,121631962.0,1200.0,"Borough Road, Elephant & Castle","Great Suffolk Street, The Borough",2022-06-20 19:59:00

In [27]:
result_general

,rentalid,duration,endstationname,startstationname,startdate
0,121447141.0,420.000,"Ansell House, Stepney","Salmon Lane, Limehouse",2022-06-16 14:07:00
1,121592389.0,840.000,"Jubilee Gardens, South Bank","Milroy Walk, South Bank",2022-06-19 21:29:00
2,121592583.0,900.000,"Borough Road, Elephant & Castle","Jubilee Gardens, South Bank",2022-06-19 21:43:00
3,121605480.0,960.000,"Tate Modern, Bankside","Cheapside, Bank",2022-06-20 10:48:00
4,121631962.0,1200.000,"Borough Road, Elephant & Castle","Great Suffolk Street, The Borough",2022-06-20 19:59:00
...,...,...,...,...,...
186429,125230184.0,830.650,"Gunmakers Lane, Old Ford","Fanshaw Street, Hoxton",2022-09-19 00:00:00
186430,125230185.0,572.144,"Westminster University, Marylebone","Drury Lane, Covent Garden",2022-09-19 00:00:00
186431,125230186.0,434.071,"Great Russell Street, Bloomsbury","Northumberland Avenue, Strand",2022-09-19 00:00:00
186432,125230187.0,1319.606,"Haggerston Road, Haggerston","Crinan Street, King's Cross",2022-09-19 00:00:00
186433,125230188.0,1821.003,"Kensington Gore, Knightsbridge","Bridge Avenue, Hammersmith",2022-09-19 00:00:00

In [28]:
result_general.dtypes

rentalid                   float64
duration                   float64
endstationname              object
startstationname            object
startdate           datetime64[ns]
dtype: object

In [29]:
result_f1=result_general[result_general['startdate']>=np.datetime64('2022-06-21 00:00:00')]
result_f2=result_f1[result_f1['startdate']<np.datetime64('2022-09-24 00:00:00')]

In [30]:
results_f = result_f2[result_f2['duration']<3600]

In [31]:
results_f

,rentalid,duration,endstationname,startstationname,startdate
7,121672526.0,960.000,"Bermondsey Street, Bermondsey","Great Suffolk Street, The Borough",2022-06-21 16:39:00
8,121676048.0,420.000,"Great Suffolk Street, The Borough","Great Suffolk Street, The Borough",2022-06-21 17:16:00
9,121680223.0,1920.000,"Great Suffolk Street, The Borough","Great Suffolk Street, The Borough",2022-06-21 17:50:00
10,121675307.0,840.000,"Great Suffolk Street, The Borough","Great Suffolk Street, The Borough",2022-06-21 17:01:00
14,121676910.0,1560.000,"Great Suffolk Street, The Borough","Great Suffolk Street, The Borough",2022-06-21 17:23:00
...,...,...,...,...,...
186429,125230184.0,830.650,"Gunmakers Lane, Old Ford","Fanshaw Street, Hoxton",2022-09-19 00:00:00
186430,125230185.0,572.144,"Westminster University, Marylebone","Drury Lane, Covent Garden",2022-09-19 00:00:00
186431,125230186.0,434.071,"Great Russell Street, Bloomsbury","Northumberland Avenue, Strand",2022-09-19 00:00:00
186432,125230187.0,1319.606,"Haggerston Road, Haggerston","Crinan Street, King's Cross",2022-09-19 00:00:00
186433,125230188.0,1821.003,"Kensington Gore, Knightsbridge","Bridge Avenue, Hammersmith",2022-09-19 00:00:00

In [32]:
len(results_f)

2558152

In [33]:
results_f.shape

(2558152, 5)

In [34]:
#results_ = results_fv.set_index('startdate')
results_f.describe(include="all")

<ipython-input-34-d9043f5d26c2>:2: FutureWarning: Treating datetime data as categorical rather than numeric in `.describe` is deprecated and will be removed in a future version of pandas. Specify `datetime_is_numeric=True` to silence this warning and adopt the future behavior now.
  results_f.describe(include="all")

,rentalid,duration,endstationname,startstationname,startdate
count,2.558152e+06,2.558152e+06,2558152,2558152,2558152
unique,NaN,NaN,801,801,94884
top,NaN,NaN,"Hyde Park Corner, Hyde Park","Hyde Park Corner, Hyde Park",2022-06-21 18:32:00
freq,NaN,NaN,19352,18950,157
first,NaN,NaN,NaN,NaN,2022-06-21 00:00:00
last,NaN,NaN,NaN,NaN,2022-09-23 23:59:00
mean,1.235411e+08,9.839036e+02,NaN,NaN,NaN
std,1.115107e+06,6.259665e+02,NaN,NaN,NaN
min,1.216376e+08,1.020000e+00,NaN,NaN,NaN
25%,1.227138e+08,5.400000e+02,NaN,NaN,NaN
50%,1.233987e+08,8.400000e+02,NaN,NaN,NaN
75%,1.244735e+08,1.320000e+03,NaN,NaN,NaN
max,1.254336e+08,3.599943e+03,NaN,NaN,NaN

In [35]:
print(results_f.isnull().sum())
results_f.dropna(inplace=True)
print(results_f.isnull().sum())

rentalid            0
duration            0
endstationname      0
startstationname    0
startdate           0
dtype: int64

<ipython-input-35-835da602d077>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  results_f.dropna(inplace=True)

rentalid            0
duration            0
endstationname      0
startstationname    0
startdate           0
dtype: int64

In [36]:

results_grouped=results_f.groupby(by=['startdate', 'startstationname', 'endstationname']).count()

In [37]:
results_grouped

                                                                                         rentalid  \
startdate           startstationname               endstationname
2022-06-21 00:00:00 Allington Street, Victoria     Doric Way , Somers Town                      1
                    Bramham Gardens, Earl's Court  Turquoise Island, Notting Hill               1
                    Exhibition Road, Knightsbridge Gas Holders, Battersea Park                  1
                    Palissy Street, Shoreditch     Charlotte Terrace, Angel                     1
                    Whitehall Place, Strand        Imperial Wharf Station, Sands End            1
...                                                                                           ...
2022-09-23 23:59:00 Millbank Tower, Pimlico        Gas Holders, Battersea Park                  1
                    Strand, Strand                 Christopher Street, Liverpool Street         2
                    Waterloo Road, South Bank      St. John Street, Finsbury                    1
                                                   Wormwood Street, Liverpool Street            1
                    York Hall, Bethnal Green       Globe Town Market, Bethnal Green             1

                                                                                         duration
startdate           startstationname               endstationname
2022-06-21 00:00:00 Allington Street, Victoria     Doric Way , Somers Town                      1
                    Bramham Gardens, Earl's Court  Turquoise Island, Notting Hill               1
                    Exhibition Road, Knightsbridge Gas Holders, Battersea Park                  1
                    Palissy Street, Shoreditch     Charlotte Terrace, Angel                     1
                    Whitehall Place, Strand        Imperial Wharf Station, Sands End            1
...                                                                                           ...
2022-09-23 23:59:00 Millbank Tower, Pimlico        Gas Holders, Battersea Park                  1
                    Strand, Strand                 Christopher Street, Liverpool Street         2
                    Waterloo Road, South Bank      St. John Street, Finsbury                    1
                                                   Wormwood Street, Liverpool Street            1
                    York Hall, Bethnal Green       Globe Town Market, Bethnal Green             1

[2361131 rows x 2 columns]

In [38]:
# results_fv=results_f.dropna()
# new_result=results_fv.set_index('startdate').groupby([pd.Grouper(freq='h'), 'startstationname', 'endstationname']).count()
# new_result

In [39]:
new_result=results_grouped
new_result['Nooftrips']=new_result['duration']

In [40]:
new_result = new_result[['Nooftrips']]

In [41]:
new_result

                                                                                         Nooftrips
startdate           startstationname               endstationname
2022-06-21 00:00:00 Allington Street, Victoria     Doric Way , Somers Town                       1
                    Bramham Gardens, Earl's Court  Turquoise Island, Notting Hill                1
                    Exhibition Road, Knightsbridge Gas Holders, Battersea Park                   1
                    Palissy Street, Shoreditch     Charlotte Terrace, Angel                      1
                    Whitehall Place, Strand        Imperial Wharf Station, Sands End             1
...                                                                                            ...
2022-09-23 23:59:00 Millbank Tower, Pimlico        Gas Holders, Battersea Park                   1
                    Strand, Strand                 Christopher Street, Liverpool Street          2
                    Waterloo Road, South Bank      St. John Street, Finsbury                     1
                                                   Wormwood Street, Liverpool Street             1
                    York Hall, Bethnal Green       Globe Town Market, Bethnal Green              1

[2361131 rows x 1 columns]

In [42]:
df = new_result.reset_index()
df = df.sort_values(by=['startdate'])
df = new_result.reset_index()
df

,startdate,startstationname,endstationname,Nooftrips
0,2022-06-21 00:00:00,"Allington Street, Victoria","Doric Way , Somers Town",1
1,2022-06-21 00:00:00,"Bramham Gardens, Earl's Court","Turquoise Island, Notting Hill",1
2,2022-06-21 00:00:00,"Exhibition Road, Knightsbridge","Gas Holders, Battersea Park",1
3,2022-06-21 00:00:00,"Palissy Street, Shoreditch","Charlotte Terrace, Angel",1
4,2022-06-21 00:00:00,"Whitehall Place, Strand","Imperial Wharf Station, Sands End",1
...,...,...,...,...
2361126,2022-09-23 23:59:00,"Millbank Tower, Pimlico","Gas Holders, Battersea Park",1
2361127,2022-09-23 23:59:00,"Strand, Strand","Christopher Street, Liverpool Street",2
2361128,2022-09-23 23:59:00,"Waterloo Road, South Bank","St. John Street, Finsbury",1
2361129,2022-09-23 23:59:00,"Waterloo Road, South Bank","Wormwood Street, Liverpool Street",1
2361130,2022-09-23 23:59:00,"York Hall, Bethnal Green","Globe Town Market, Bethnal Green",1

In [43]:
# df['startdate'] = df['Starate'].apply(lambda x: x.strftime(date_format))

In [44]:
df

,startdate,startstationname,endstationname,Nooftrips
0,2022-06-21 00:00:00,"Allington Street, Victoria","Doric Way , Somers Town",1
1,2022-06-21 00:00:00,"Bramham Gardens, Earl's Court","Turquoise Island, Notting Hill",1
2,2022-06-21 00:00:00,"Exhibition Road, Knightsbridge","Gas Holders, Battersea Park",1
3,2022-06-21 00:00:00,"Palissy Street, Shoreditch","Charlotte Terrace, Angel",1
4,2022-06-21 00:00:00,"Whitehall Place, Strand","Imperial Wharf Station, Sands End",1
...,...,...,...,...
2361126,2022-09-23 23:59:00,"Millbank Tower, Pimlico","Gas Holders, Battersea Park",1
2361127,2022-09-23 23:59:00,"Strand, Strand","Christopher Street, Liverpool Street",2
2361128,2022-09-23 23:59:00,"Waterloo Road, South Bank","St. John Street, Finsbury",1
2361129,2022-09-23 23:59:00,"Waterloo Road, South Bank","Wormwood Street, Liverpool Street",1
2361130,2022-09-23 23:59:00,"York Hall, Bethnal Green","Globe Town Market, Bethnal Green",1

In [45]:
dates_for_catherine=df

In [46]:
path_cat='london-bss-colab/dates_for_catherine.csv'

In [47]:
dates_for_catherine.to_csv(path_or_buf=path_cat)

In [48]:
df.dtypes

startdate           datetime64[ns]
startstationname            object
endstationname              object
Nooftrips                    int64
dtype: object

In [49]:
from sklearn.preprocessing import OrdinalEncoder

In [50]:
df["date_code"] = 0
df["so_code"] = 0
df["sd_code"] = 0
ord_enc = OrdinalEncoder()
df["date_code"] = ord_enc.fit_transform(df[["startdate"]])
df["so_code"] = ord_enc.fit_transform(df[["startstationname"]])
df["sd_code"] = ord_enc.fit_transform(df[["endstationname"]])

In [51]:
df

,startdate,startstationname,endstationname,Nooftrips,date_code,so_code,sd_code
0,2022-06-21 00:00:00,"Allington Street, Victoria","Doric Way , Somers Town",1,0.0,22.0,202.0
1,2022-06-21 00:00:00,"Bramham Gardens, Earl's Court","Turquoise Island, Notting Hill",1,0.0,94.0,719.0
2,2022-06-21 00:00:00,"Exhibition Road, Knightsbridge","Gas Holders, Battersea Park",1,0.0,241.0,274.0
3,2022-06-21 00:00:00,"Palissy Street, Shoreditch","Charlotte Terrace, Angel",1,0.0,514.0,139.0
4,2022-06-21 00:00:00,"Whitehall Place, Strand","Imperial Wharf Station, Sands End",1,0.0,786.0,371.0
...,...,...,...,...,...,...,...
2361126,2022-09-23 23:59:00,"Millbank Tower, Pimlico","Gas Holders, Battersea Park",1,94883.0,452.0,274.0
2361127,2022-09-23 23:59:00,"Strand, Strand","Christopher Street, Liverpool Street",2,94883.0,685.0,147.0
2361128,2022-09-23 23:59:00,"Waterloo Road, South Bank","St. John Street, Finsbury",1,94883.0,758.0,661.0
2361129,2022-09-23 23:59:00,"Waterloo Road, South Bank","Wormwood Street, Liverpool Street",1,94883.0,758.0,794.0
2361130,2022-09-23 23:59:00,"York Hall, Bethnal Green","Globe Town Market, Bethnal Green",1,94883.0,799.0,282.0

In [52]:
obj_df = df.select_dtypes(include=['object']).copy()

In [53]:
obj_df.head()

                 startstationname                     endstationname
0      Allington Street, Victoria            Doric Way , Somers Town
1   Bramham Gardens, Earl's Court     Turquoise Island, Notting Hill
2  Exhibition Road, Knightsbridge        Gas Holders, Battersea Park
3      Palissy Street, Shoreditch           Charlotte Terrace, Angel
4         Whitehall Place, Strand  Imperial Wharf Station, Sands End

In [54]:
coords = df[['so_code','sd_code','date_code']]

In [55]:
coords.shape

(2361131, 3)

In [56]:
values = df['Nooftrips']

In [57]:
values.shape

(2361131,)

In [58]:
coords = np.array(coords, dtype=np.int64).T
values = np.array(values, dtype=np.float64)

In [59]:
tensor = sparse.COO(coords, data=values)

In [60]:
print(tensor)

<COO: shape=(801, 801, 94884), dtype=float64, nnz=2361131, fill_value=0.0>

In [61]:
type(tensor)

sparse._coo.core.COO

In [62]:
tensor.nbytes / 1e9

0.075556192

In [63]:
!pip install tensorly

Requirement already satisfied: tensorly in /usr/local/lib/python3.10/dist-packages (0.8.1)
Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from tensorly) (1.23.5)
Requirement already satisfied: scipy in /usr/local/lib/python3.10/dist-packages (from tensorly) (1.10.1)

In [64]:
import tensorly as tl
from tensorly.decomposition import tucker

In [65]:
#

In [66]:
# Rank of Tucker decomposition
tucker_rank = [25, 25, 30]

In [67]:
core, factors = tucker(tensor, rank=tucker_rank, init='random', tol=10e-5,random_state=12345)

In [70]:
import tensorflow as tf

In [69]:
type(core)

numpy.ndarray

In [71]:
core_tensor=tf.convert_to_tensor(core)
dataset_core_tensor=tf.data.Dataset.from_tensors(core_tensor)
path_core='london-bss-colab/core_folder_3mo_summer'
dataset_core_tensor.save(path_core)

In [75]:
path_factors='london-bss-colab/factors_folder_3mo_summer/'
# os.makedirs(path_factors)
for i,factor in enumerate(factors):
  df=pd.DataFrame(factor)
  df.to_csv(path_factors+str(i)+'.csv')

In [ ]:
fig, axs = plt.subplots(5, 3)
fig.set_size_inches(18.5, 10.5)
axs[0, 0].scatter(x=range(len(factors[0])), y=np.transpose(factors[0])[0])
axs[0, 1].scatter(x=range(len(factors[1])), y=np.transpose(factors[1])[0])
axs[0, 2].plot(np.transpose(factors[2])[0])

axs[1, 0].scatter(x=range(len(factors[0])), y=np.transpose(factors[0])[1])
axs[1, 1].scatter(x=range(len(factors[1])), y=np.transpose(factors[1])[1])
axs[1, 2].plot(np.transpose(factors[2])[1])

axs[2, 0].scatter(x=range(len(factors[0])), y=np.transpose(factors[0])[2])
axs[2, 1].scatter(x=range(len(factors[1])), y=np.transpose(factors[1])[2])
axs[2, 2].plot(np.transpose(factors[2])[2])

axs[3, 0].scatter(x=range(len(factors[0])), y=np.transpose(factors[0])[3])
axs[3, 1].scatter(x=range(len(factors[1])), y=np.transpose(factors[1])[3])
axs[3, 2].plot(np.transpose(factors[2])[3])

axs[4, 0].scatter(x=range(len(factors[0])), y=np.transpose(factors[0])[4])
axs[4, 1].scatter(x=range(len(factors[1])), y=np.transpose(factors[1])[4])
axs[4, 2].plot(np.transpose(factors[2])[4])