In [24]:
import requests
import json  
import pandas as pd

In [25]:
response= requests.get('https://api.tfl.gov.uk/BikePoint/')
stations = response.json()

In [26]:
data =  pd.DataFrame()
s_names = []
s_lat = []
s_lon = []

NbBikes = []
NbEmptyDocks = []
NbDocks = []
NbStandardBikes = []
NbEBikes = []
s_id = []

In [27]:
len_lat = 0
for station in stations:
    s_names.append(station['commonName'])
    s_lat.append(float(station['lat']))
    s_lon.append(float(station['lon']))
    for add_property in station['additionalProperties']:
        if add_property['key'] == 'NbBikes':
            NbBikes.append(int(add_property['value']))
        if add_property['key'] == 'NbEmptyDocks':
            NbEmptyDocks.append(int(add_property['value']))     
        if add_property['key'] == 'NbDocks':
            NbDocks.append(int(add_property['value']))
        if add_property['key'] == 'NbStandardBikes':
            NbStandardBikes.append(int(add_property['value']))
        if add_property['key'] == 'NbEBikes':
            NbEBikes.append(int(add_property['value']))
        if add_property['key'] == 'TerminalName':
            s_id.append(int(add_property['value']))

In [28]:
len(s_lat)

786

In [29]:
data['Station_name'] = s_names
data['s_lat'] = s_lat
data['s_lon'] = s_lon
data['s_num_bikes'] = NbBikes
data['s_num_empty_docks'] = NbEmptyDocks
data['s_num_std_bikes'] = NbStandardBikes
data['s_num_e-bikes'] = NbEBikes
data['s_num_docks'] = data['s_num_bikes'] + data['s_num_empty_docks']
data['s_id'] = s_id

In [30]:
data

,Station_name,s_lat,s_lon,s_num_bikes,s_num_empty_docks,s_num_std_bikes,s_num_e-bikes,s_num_docks,s_id
0,"River Street , Clerkenwell",51.529163,-0.109970,0,17,0,0,17,1023
1,"Phillimore Gardens, Kensington",51.499606,-0.197574,25,10,25,0,35,1018
2,"Christopher Street, Liverpool Street",51.521283,-0.084605,16,15,15,1,31,1012
3,"St. Chad's Street, King's Cross",51.530059,-0.120973,4,19,4,0,23,1013
4,"Sedding Street, Sloane Square",51.493130,-0.156876,25,0,25,0,25,3420
...,...,...,...,...,...,...,...,...,...
781,"Aintree Street, Fulham",51.481021,-0.209973,9,15,9,0,24,200098
782,"Great Suffolk Street, The Borough",51.501732,-0.100292,6,14,6,0,20,200200
783,"Westbourne Park Road, Portobello",51.517870,-0.201005,0,23,0,0,23,300057
784,"Hereford Road, Bayswater",51.513735,-0.193487,0,22,0,0,22,1016
785,"Pembridge Villas, Notting Hill",51.511084,-0.197524,0,16,0,0,16,2589

In [31]:
stations[0]['additionalProperties']

[{'$type': 'Tfl.Api.Presentation.Entities.AdditionalProperties, Tfl.Api.Presentation.Entities',
  'category': 'Description',
  'key': 'TerminalName',
  'sourceSystemKey': 'BikePoints',
  'value': '001023',
  'modified': '2023-08-29T07:10:19.457Z'},
 {'$type': 'Tfl.Api.Presentation.Entities.AdditionalProperties, Tfl.Api.Presentation.Entities',
  'category': 'Description',
  'key': 'Installed',
  'sourceSystemKey': 'BikePoints',
  'value': 'true',
  'modified': '2023-08-29T07:10:19.457Z'},
 {'$type': 'Tfl.Api.Presentation.Entities.AdditionalProperties, Tfl.Api.Presentation.Entities',
  'category': 'Description',
  'key': 'Locked',
  'sourceSystemKey': 'BikePoints',
  'value': 'false',
  'modified': '2023-08-29T07:10:19.457Z'},
 {'$type': 'Tfl.Api.Presentation.Entities.AdditionalProperties, Tfl.Api.Presentation.Entities',
  'category': 'Description',
  'key': 'InstallDate',
  'sourceSystemKey': 'BikePoints',
  'value': '1278947280000',
  'modified': '2023-08-29T07:10:19.457Z'},
 {'$type': 'Tfl.Api.Presentation.Entities.AdditionalProperties, Tfl.Api.Presentation.Entities',
  'category': 'Description',
  'key': 'RemovalDate',
  'sourceSystemKey': 'BikePoints',
  'value': '',
  'modified': '2023-08-29T07:10:19.457Z'},
 {'$type': 'Tfl.Api.Presentation.Entities.AdditionalProperties, Tfl.Api.Presentation.Entities',
  'category': 'Description',
  'key': 'Temporary',
  'sourceSystemKey': 'BikePoints',
  'value': 'false',
  'modified': '2023-08-29T07:10:19.457Z'},
 {'$type': 'Tfl.Api.Presentation.Entities.AdditionalProperties, Tfl.Api.Presentation.Entities',
  'category': 'Description',
  'key': 'NbBikes',
  'sourceSystemKey': 'BikePoints',
  'value': '0',
  'modified': '2023-08-29T07:10:19.457Z'},
 {'$type': 'Tfl.Api.Presentation.Entities.AdditionalProperties, Tfl.Api.Presentation.Entities',
  'category': 'Description',
  'key': 'NbEmptyDocks',
  'sourceSystemKey': 'BikePoints',
  'value': '17',
  'modified': '2023-08-29T07:10:19.457Z'},
 {'$type': 'Tfl.Api.Presentation.Entities.AdditionalProperties, Tfl.Api.Presentation.Entities',
  'category': 'Description',
  'key': 'NbDocks',
  'sourceSystemKey': 'BikePoints',
  'value': '19',
  'modified': '2023-08-29T07:10:19.457Z'},
 {'$type': 'Tfl.Api.Presentation.Entities.AdditionalProperties, Tfl.Api.Presentation.Entities',
  'category': 'Description',
  'key': 'NbStandardBikes',
  'sourceSystemKey': 'BikePoints',
  'value': '0',
  'modified': '2023-08-29T07:10:19.457Z'},
 {'$type': 'Tfl.Api.Presentation.Entities.AdditionalProperties, Tfl.Api.Presentation.Entities',
  'category': 'Description',
  'key': 'NbEBikes',
  'sourceSystemKey': 'BikePoints',
  'value': '0',
  'modified': '2023-08-29T07:10:19.457Z'}]